language: node_js

node_js:
- node

cache:
  directories:
  - node_modules

before_script:
- npm install -g codecov

script:
- npm run unit
- codecov --token=$CODECOV_TOKEN

deploy:
  provider: npm
  email: laomao800@gmail.com
  api_key:
    secure: KValExnRDgffAGXfPqfNO6gd/6H8V+mu9AMV3j9OpxhkSmkTB/D5wR8TP3hpCdpJVlTmcpSa9JKNgsuObn2mXBpKrZ8np3KucvUZ2dDbBj3+dhRxdXzwYRl5CR3m+KYzb8AScDNQjABhsRfwgwKp8aeGCHll5g1e8tSz3ZXFcJzc987vpxNLbuObv/9YVYJsySPzYrlbl+Tj4fiDkiXENjqNkvC2j37E5zr2ymbjKP6AQBmtIY0EiJKNyIlu5onepOGHqKUuwm8r8X8tP0dOBHUBgo6OEZYFMQtevxT3MPR5D0dLUz24EfSXOJUAbCXcxf7hLcusR/rFdQjWTqJEOlQSw99NjLHngYVpVcFBwHbyXORvgtaxJry86+HqAFEm8PG9FR3B6pNv1I99jg/9IQCeNmU0szarjEywYGObBnhKX0wyST6NInwwfjqt8xq8WkDnbYxvBkweqANIebTx1fHtdhb8tFANMnLCdYgDKqWngX1+JO6wCQRAnaVmFpjzvmSUNd1XFnHWZfXmCvULhyz6fPy1NDFSdaeldvmDeDMX9FkjlRM6DNohGDOrofvzs+SEVF8QM9VITnZvKCLI7kWfyCUHwodjIt8PWCUFfspIJuG9nT6cgOVSplxsD5PTKWCWi7Firokf+luNIRuFAxPNNm9w5AF/iUw4E/OBCl8=
  on:
    tags: true
    repo: laomao800/vue-item-list-selector

env:
  global:
    secure: UhTku4WH6kdjCDx4M1lTOQzOKHNOsGrVq6+yRFAuhhJbB+OVzO+m+hNsCAAfIWr2a/TtJU0GECqtHBm6I34/N57X5t0lrtDh0hcCEDxWLxzmDQAs/FnjhbwN2e3kU9zH94vRLLz9dGcokge0mG9HlJ9AdLVdPQcUvZ+Ey8PDTgycAoVyv6Xn/uABLMd2/9+Ig8xAraXbYImktTS4NOjW5l8fvQQS6U50hSGdGY9khxX7KYMa8Dajvy0LAAAhB6dS/eRGCtMk0tfvUjEGPeYkT3Uo3b+f1FlXGxbCcdlIhQdQEzPKTQCeIJstpfHr4W+G0uoeFQ9m59UVpZsUTPZk35W1j/gVUcV1GUHCYcdAf0XvwSssz+bMBRDc/8qp3OTtS0ugNkiJNOGS8oxbsXoG638d8YQJMRUSzy7qi0Wkad9omZhX55o109q1gGePl5LvJ3JkvrmlOKXiIXl6ekwT+KYB6JsoyLx3h7G4HqUF55F95UZlDsmzuMI1SaeWZnlS+wzO68P0IKVkCHAoP/FsppLxJH8V+NM/8J+2AWHEHaYPzRTQmet3ax016vgEyGNHTSO0/vA+lT1aN5RzbNeacDL4MtnvjuJS13H9QU7wvr0gN/RHfsrV4i5+rSiUbCyTr/E4maR0p+XHQQDLvafOMlduyUvJGgbQm9tqeZ6rfHw=
